name: Backend Scraper Continuous Integration

on:
  push:
    paths:
      - "backend/NodeScrapers/**"

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/NodeScrapers

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm test