name: Frontend Continuous Integration

on:
  push:
    paths:
      - "frontend/**"

  workflow_dispatch:

jobs:
  front-end-continuous-integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - run: npm run test